################################################################################
################################ Go shortcuts ##################################
################################################################################

build:
	go build -o quick-dl

run:
	go run quick-dl.go

clean:
	rm quick-dl

dev:
	air

install:
	go install

.PHONY: build run clean dev install